spring:
    application:
      name: EstacionABC
    thymeleaf:
      cache: false

server:
  error:
    include-message: always
    include-binding-errors: always

#logging:
#  level:
#    web: DEBUG